{% set name = "django-large-image" %}
{% set version = "0.8.1" %}

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://pypi.io/packages/source/{{ name[0] }}/{{ name }}/django-large-image-{{ version }}.tar.gz
  sha256: e656fe375f1711b423972f5d2b496d4271edef6c60af26bcb5d36889c3426797

build:
  noarch: python
  script: {{ PYTHON }} -m pip install . -vv
  number: 0

requirements:
  host:
    - pip
    - python >=3.8
  run:
    - django
    - djangorestframework
    - drf-yasg
    - filelock
    - large-image >=1.15
    - python >=3.8

test:
  imports:
    - django_large_image
  commands:
    - pip check
  requires:
    - pip

about:
  home: https://github.com/girder/django-large-image
  license: Apache-2.0
  license_file: LICENSE
  summary: Dynamic tile server in Django built on top of large-image (and GDAL)
  description: |
    django-large-image is an abstraction of large-image for use with
    django-rest-framework providing viewset mixins for endpoints to work with
    large images (Cloud Optimized GeoTiffs or medical image formats) in Django.

extra:
  recipe-maintainers:
    - banesullivan
    - manthey
    - kwrobot
